language: java
jdk:
  - oraclejdk8
  - openjdk8
install: true

script:
  - "mvn clean package -Dmaven.test.skip=true"

#script:
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#  - cd docker
#  - docker build -t hehety/godfs:latest .
#  - docker push hehety/godfs